version: '3.8'

services:
  php:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
   - "8080:80"
   volumes:
    - ./src:/var/www/html
   depends_on:
    - db

  db:
    image: postgres:latest
    environment:
     POSTGRES_USER: myuser
     POSTGRES_PASSWORD: mypassword
     POSTGRES_DB: mydb
    ports:
      - "5432:5432"
