name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 13.239.136.254/
          username: WayanPasek
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/myproject
            ./deploy.sh
